#!/usr/bin/env bash

# Update package index
# Install Nginx
# Create the directory for Nginx default site
# Create a simple HTML page

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
