#!/usr/bin/env bash
# Uses while and if to display Best School and Hi on 9th iteration
i=1
while [ $i -le 10 ];
do
    if [ $i -eq 10 ];
    then
       echo "Hi"
    fi
    echo "Best school"
    ((i++))
done
