#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 54.144.132.7
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
